---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
  labels:
    app.kubernetes.io/name: web-app
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login</title>
        <link rel="stylesheet" href="styles.css">
    </head>
    <body>
        <div class="login-container">
            <form class="login-form">
                <h2>Login</h2>
                <div class="input-group">
                    <input type="text" required>
                    <label>Username</label>
                </div>
                <div class="input-group">
                    <input type="password" required>
                    <label>Password</label>
                </div>
                <button type="submit">Login</button>
                <p class="signup-text">
                    Don't have an account? <a href="#">Sign Up</a>
                </p>
            </form>
        </div>
    </body>
    </html>
  style.css: |
    body {
      margin: 0;
      padding: 0;
      font-family: 'Arial', sans-serif;
      background: linear-gradient(135deg, #71b7e6, #9b59b6);
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .login-container {
      background: white;
      padding: 40px 60px;
      border-radius: 10px;
      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
      text-align: center;
    }
    .login-form h2 {
      margin-bottom: 30px;
      font-size: 30px;
      color: #333;
    }
    .input-group {
      position: relative;
      margin-bottom: 30px;
    }
    .input-group input {
      width: 100%;
      padding: 10px;
      background: #f1f1f1;
      border: none;
      border-radius: 5px;
      outline: none;
      font-size: 16px;
    }
    .input-group label {
      position: absolute;
      left: 10px;
      top: 50%;
      transform: translateY(-50%);
      color: #aaa;
      pointer-events: none;
      transition: 0.3s;
    }
    .input-group input:focus + label,
    .input-group input:valid + label {
      top: -10px;
      left: 5px;
      color: #9b59b6;
      font-size: 12px;
      background: white;
      padding: 0 5px;
    }
    button {
      width: 100%;
      padding: 10px;
      background: #9b59b6;
      border: none;
      border-radius: 5px;
      color: white;
      font-size: 16px;
      cursor: pointer;
      transition: background 0.3s;
    }
    button:hover {
      background: #8e44ad;
    }
    .signup-text {
      margin-top: 20px;
      color: #333;
    }
    .signup-text a {
      color: #9b59b6;
      text-decoration: none;
      font-weight: bold;
    }
    .signup-text a:hover {
      text-decoration: underline;
    }
